export const LOCAL_STORAGE_TOKEN_NAME = 'token';
export const DEFAULT_PAGE_SIZE = 10;
export const DEFAULT_DATE_FORMAT = 'dd/MM/YYYY';
export const POPULAR_CARS_AND_TRUCKS_MODELS = [
  { name: 'Ford F-150' },
  { name: 'Ford F-250' },
  { name: 'Ford F-350' },
  { name: 'Chevrolet Silverado 1500' },
  { name: 'Chevrolet Silverado 2500HD' },
  { name: 'Chevrolet Silverado 3500HD' },
  { name: 'Ram 1500' },
  { name: 'Ram 2500' },
  { name: 'Ram 3500' },
  { name: 'GMC Sierra 1500' },
  { name: 'GMC Sierra 2500HD' },
  { name: 'GMC Sierra 3500HD' },
  { name: 'Toyota Tundra' },
  { name: 'Nissan Titan' },
  { name: 'GMC Canyon' },
  { name: 'Chevrolet Colorado' },
  { name: 'Ford Ranger' },
  { name: 'Toyota Tacoma' },
  { name: 'Nissan Frontier' },
  { name: 'International LT' },
  { name: 'Freightliner Cascadia' },
  { name: 'Kenworth T680' },
  { name: 'Peterbilt 579' },
  { name: 'Volvo VNL' },
  { name: 'Mack Anthem' },
  { name: 'Western Star 5700' },
  { name: 'Kenworth T880' },
  { name: 'Peterbilt 389' },
  { name: 'Volvo VHD' },
  { name: 'Mack Granite' },
  { name: 'Western Star 4900' },
  { name: 'Freightliner M2 106' },
  { name: 'International HV' },
  { name: 'Kenworth T270' },
  { name: 'Peterbilt 337' },
  { name: 'Volvo VNR' },
  { name: 'Mack MD' },
  { name: 'Western Star 4700' },
  { name: 'Freightliner 108SD' },
  { name: 'International CV' },
  { name: 'Kenworth T370' },
  { name: 'Peterbilt 348' },
  { name: 'Volvo VNX' },
  { name: 'Mack LR' },
  { name: 'Western Star 4800' },
  { name: 'Freightliner 114SD' },
  { name: 'International MV' },
  { name: 'Kenworth T440' },
  { name: 'Peterbilt 567' },
  { name: 'Volvo VAH' },
  { name: 'Mack TerraPro' },
  { name: 'Western Star 6900' },
];
export const FORM_ENTRY_DATA_COLS = [
  { field: 'date', header: 'CONTROL_DATE' },
  { field: 'isValidFrom', header: 'VALID_FROM' },
  { field: 'validTo', header: 'VALID_TO' },
  { field: 'isAuthorized', header: 'FINAL_STATUS' },
];

export const DRIVER_INFO_COLS = [
  { field: 'firstName', header: 'FIRST_NAME' },
  { field: 'lastName', header: 'LAST_NAME' },
  { field: 'driverLicenseNumber', header: 'DRIVER_LICENSE_NUMBER' },
];

export const VEHICLE_TANK_INFO_COLS = [
  { field: 'plateNumber', header: 'PLATE_NUMBER' },
  { field: 'model', header: 'MODEL' },
  { field: 'company', header: 'COMPANY' },
  { field: 'driver', header: 'DRIVER' },
];
